<?php

/**
 * @file
 * Enables the site to scrape search results from OER Commons site 
 * and imports the results into "Resource" nodes.
 * 
 * This module also provides helper functions and plugins for other migrations
 */

 use Drupal\migrate\Plugin\MigrateSourceInterface;
 use Drupal\migrate\Row;
 use Drupal\migrate\Plugin\MigrationInterface;
 use Drupal\migrate\MigrateSkipRowException;

/**
 * Implements hook_migrate_prepare_row().
 */
function h5p_scrape_oer_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  /* Perform some data processing on the data coming from the user CSV file */
  if ($migration->id() == "h5p_migrate_wordpress_users") {
  }

  /* Perform some data processing on the data coming from the Resources CSV file */
  if ($migration->id() == "h5p_migrate_wordpress_resources") {
  }

  /* Perform some data processing on the data coming from the Resources CSV file */
  if ($migration->id() == "h5p_migrate_wordpress_resources_docclient") {
    /* Stop the migration if field 'id' is empty in the XLSX file */
    if (!$row->getSourceProperty('id')) {
    return FALSE;
   }
  }
}